### ISSUE TITLE
Pulumi tokens improvements (individual, org or otherwise)

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#79]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It's great to know when a token was last used 👍, however, these tokens could get some additional helpful features:

- Display the token creation date
- Recommend a token rotation if the token is older than 180 days
- Restrict the use of a Token based on one or more IP addresses / CIDR
- Token expiry date after which the token become unusable
- Enable/Disable tokens

### Affected area/feature

* Pulumi service

**Comment by HenryNguyen5** [comment]
Related to https://github.com/pulumi/service-requests/issues/160

**Comment by tusharshahrs** [comment]
Related to # [172](https://github.com/pulumi/service-requests/issues/172)

**Comment by caseyyh** [comment]
Thanks Aurelian for filing the issue!

> It's great to know when a token was last used 👍, however, these tokens could get some additional helpful features:
> Recommend a token rotation if the token is older than 180 days
> Token expiry date after which the token become unusable

Was completed in:


https://github.com/pulumi/pulumi-service/issues/17736

> Display the token creation date

Is being tracked in:

https://github.com/pulumi/pulumi-service/issues/20822

> Restrict the use of a Token based on one or more IP addresses / CIDR
> Enable/Disable tokens

We likely won't tackle enable/disable tokens, since we currently support deletion of tokens and token expiry. Token restriction would also take additional work that we will evaluate at a future point.

Please do open an issue if you have any more ideas, thanks!
